import axios from 'axios';

/**
 * Sends a base64 encoded image to the Gemini API to generate a description.
 * 
 * @param {string} base64Image - The base64 encoded image to be processed.
 * @returns {Promise<string>} The description generated by the Gemini API.
 */
export const getDescriptionFromGemini = async (base64Image) => {
  try {
    // Send a POST request to the Gemini API endpoint with the image data
    const response = await axios.post('http://192.168.0.104:3000/gemini', {
      image: base64Image
    });

    // Return the description from the response data
    return response.data.description;
  } catch (error) {
    // Handle any errors that occur during the request
    console.error('Error fetching description from Gemini:', error);
    throw error;
  }
};
